### ISSUE TITLE
Network Lifecycle Management

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry/bosh-aws-cpi-release#89]
BOSH [v268.0.1](https://github.com/cloudfoundry/bosh/releases/tag/v268.0.1) introduces beta functionality of [network lifecycle management](https://docs.google.com/document/d/1akr17Iep99fCYNqZQv9uoxar7qF04U40O6cYoAsg3lA/edit). Can we add support for this at the AWS CPI?

**Comment by belinda-liu** [comment]
Hey @frodenas, 
Sorry for the late response. We have no plans at the moment to add support for network lifecycle management for AWS. As of now the feature is still very much in progress on the vSphere CPI, once that work is completed I think we will revisit the AWS CPI. 
Thank you for the feedback, we'll keep it in mind.

**Comment by frodenas** [comment]
Director has support for this since [version 268.1.0](https://bosh.io/docs/managed-networks/), the vSphere CPI completed the work in [v51](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/releases/tag/v51) (see [vSphere CPI Managed Networks documentation](https://bosh.io/docs/vsphere-cpi/#managed-networks)). Can you please revisit the AWS CPI now?

**Comment by belinda-liu** [comment]
Hey @frodenas,

I realize my last comment might have been a little unclear. Adding this feature to the AWS CPI is definitely on the long term roadmap, but it isn't a priority right now. Currently we're working on merging in the PR that will add support for updating managed networks in the director with respect to the vSphere CPI, which is why I mentioned that it is still in progress.
As far as I know we don't currently have an established process of moving a feature out of beta, so that will be a conversation that needs to happen before support for manage networks is introduced in other CPIs. If you want to be a part of that conversation, I would sync up with @mfine. 

Thanks again for the poke, we can keep this issue open as a reminder.

**Comment by frodenas** [comment]
Understood, thanks for the update @belinda-liu
